name: Daily Stock Analysis

on:
  schedule:
    # 每天北京时间16:30运行（收盘后）
    - cron: '30 8 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis pipeline
      env:
        API_LICENCE: ${{ secrets.API_LICENCE }}
      run: |
        python run_pipeline.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        keep_files: false
        force_orphan: true
    
    - name: Create summary
      run: |
        echo "## 股票分析完成" >> $GITHUB_STEP_SUMMARY
        echo "- 分析时间: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- 仪表板已部署到 GitHub Pages" >> $GITHUB_STEP_SUMMARY
        echo "- [查看仪表板](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY
